Recipe.create!([
  {title: "Ratatouille", chef: "Remy", ingredients: "1 Large Zucchini, 1 Large Yellow Summer Squash, 2 Small Eggplants, 1 Red Bell Pepper, 1/2 Small Yellow Onion, 2 Garlic Cloves, 15 oz. can Crushed Tomatoes, Fresh Thyme, 1 tsp Salt", directions: "mix them", image_url: "https://media.chefdehome.com/740/0/0/ratatouille/ratatouille-casserole.jpg", prep_time: 43},
  {title: "Lagsana", chef: "Garfield", ingredients: "tire, old shoe, peppermint toothpaste, noodles", directions: "pile ingredients into pan, heat to 350 degrees, wait for fire alarm", image_url: "https://cafedelites.com/wp-content/uploads/2018/01/Mamas-Best-Lasagna-IMAGE-43.jpg", prep_time: 400},
  {title: "Hand Sandwich", chef: "Josh", ingredients: "left hand, right hand, lettuce, mayo, avocado", directions: "place left palm up, lay other ingredients on top, finish with right, place hands together, good night, wisconsin!", image_url: "https://i.pinimg.com/originals/3a/1a/4e/3a1a4e0fb7c54c1894ecc08d64851628.jpg", prep_time: 15},
  {title: "Cookies", chef: "Cookie Monster", ingredients: "cookie mix, milk, eggs, love", directions: "cookie, cookie, cookie, darn, should have bought eggs", image_url: "http://1.bp.blogspot.com/-w-i7-dRn_V0/TeZP9aAxPBI/AAAAAAAAAR4/8E_-JCJlEmQ/s1600/Apri2011+055pwm.jpg", prep_time: 400},
  {title: "ABC Gum", chef: "Mcgruff the Crime Dog", ingredients: "gum, loafer", directions: "remove gum from show, chew", image_url: "http://transatlanticmom.com/wp-content/uploads/2012/01/chewed-gum.jpg", prep_time: 30},
  {title: "Raw Egg", chef: "Bad Josh", ingredients: "live chicken, pair of gloves", directions: "place gloves on hands, grip chickens body, squeeze gently", image_url: "https://s3-us-west-2.amazonaws.com/hobbyfarms.com/wp-content/uploads/2018/02/21222019/raw-egg-289494134-600x347.jpg", prep_time: 5},
  {title: "Baked Beans", chef: "Frank Bush", ingredients: "can, beans, fire", directions: "out of the can, into the man", image_url: "https://www.connoisseurusveg.com/wp-content/uploads/2016/05/vegan-baked-beans-fb.jpg", prep_time: 1},
  {title: "Bubbles", chef: "Mr. Bubbles", ingredients: "soap, water", directions: "fill tub, add soap, swish", image_url: "https://i.pinimg.com/originals/a9/3f/11/a93f11b692924f7dc50b095c70aa9d7a.jpg", prep_time: 15},
  {title: "Bibimbap", chef: "Patty", ingredients: "rice, veggies, red pepper paste", directions: "mix em all", image_url: "https://assets.dmagstatic.com/wp-content/uploads/2018/02/korean-food-guide-dallas.jpg", prep_time: 15}
])